[package]
name = "filename_replace_whitespace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
log = "0.4.17"
env_logger = "0.9.0"
error-stack = "0.1.1"
